### ISSUE TITLE
Make mayavi optional dependency

### ISSUE THREAD

**Issue by rzetter** [bfieldtools/bfieldtools#15]
Mayavi can make installation harder due to vtk dependency, and is also responsible for over half (~2.7 s) of the import time of bfieldtools. Mayavi could be an optional dependency, or at least imported lazily.

**Comment by rzetter** [comment]
> Move "from mayavi import mlab" to local import inside the functions that use it?

Current status: @anttimc moved imports into the functions that need them. Mayavi still present in requirements.txt

**Comment by anttimc** [comment]
Have the import times decreased? I remember that was an issue in some tests,, although they did not contain any visualization.

**Comment by rzetter** [comment]
Yes, they were ~cut in half now that mayavi is not imported when you import the entire package!

**Comment by anttimc** [comment]
Mayavi should not be needed for the installlation now. How to test this? New branch and test build without mayavi in travis?
