### ISSUE TITLE
CVXPY 1.1 incompatibility

### ISSUE THREAD

**Issue by rzetter** [bfieldtools/bfieldtools#28]
Python seems to crash without error messages when using CVXPY 1.1 (when passing the problem to the solver), while 1.0.x works. Will investigate.

**Comment by rzetter** [comment]
Bug seems to be related to how we were using parametrized problems in CVXPY, probably how we were populating the parameters with data. This was meant to allow for skipping the canonicalization time for subsequent solves of the same problem (but with different data). As there is no such time advantage to be had for our problems (but rather a time penalty, see https://github.com/cvxgrp/cvxpy/issues/1058 and the WIP pull request https://github.com/cvxgrp/cvxpy/pull/1059), I'm removing the parametrization for the time being. The removal of parametrization also fixes the 1.1 incompatibility, fixed in 78d2bc6e61cb946a4490f99e38d21e8bcc69b5a2.

**Comment by SteveDiamond** [comment]
FYI parametrization should now have a time advantage, with the latest CVXPY patch.

**Comment by rzetter** [comment]
Great stuff, thanks for taking the time to write here as well! I'll 're-enable' parametrization and make sure our package works with the 1.1-branch of CVXPY!

**Comment by rzetter** [comment]
Re-added parametrized (DPP) formulation as an option (commit 212fd9d), CVXPY dependency version requirement bumped to >=1.1.5. Still not the default setting since the initial parametrized canonicalization is still quite a bit slower than non-parametrized problems.
