### ISSUE TITLE
edit/create new meshes and geometries

### ISSUE THREAD

**Issue by rth0mas** [bfieldtools/bfieldtools#33]
I'm interested in defining my own geometries, eg, for coils and magnetic shields. The current example library uses .obj and .stl files. What are the file requirements/configurations for creating new geometries?

**Comment by rzetter** [comment]
Hello Thomas! The mesh backend in bfieldtools is provided by trimesh (https://github.com/mikedh/trimesh), which supports a multitude of file formats:
>Import meshes from binary/ASCII STL, Wavefront OBJ, ASCII OFF, binary/ASCII PLY, GLTF/GLB 2.0, 3MF, XAML, 3DXML, etc.

To create your own geometries, there are lots of options. The surface meshes should have high enough resolution to (this will depend on your problem), and should preferably be meshed with FEM/physics modelling in mind.

There are a lot of tools to create such meshes, but here are some GUI alternatives :

FreeCAD (uses gmsh as a back-end): https://wiki.freecadweb.org/FEM_Mesh

gmsh can also be used directly, but has a pretty steep learning curve: https://gmsh.info/

COMSOL is a huge commercial (expensive) FEM modelling package, and it has a easy-to use GUI for creating geometries and meshing them. If you have easy access to COMSOL, it's a good solution. If not, it's not at all worth buying for this purpose only.

**Comment by anttimc** [comment]
To generate good-quality meshes for simple geometries in python see this https://github.com/nschloe/meshzoo

**Comment by rzetter** [comment]
That looks like a great tool, thanks for the tip!
