### ISSUE TITLE
Missing argument on np.ones?

### ISSUE THREAD

**Issue by svejgaard** [bfieldtools/bfieldtools#36]
Hi guys,

At some point I came across this, and my python did not like to do the division.
```python
    if deflate:
        evals = eigh(quadratic_matrix, eigvals=(0, 1), eigvals_only=True)
        if abs(evals[0]) < 1e-8 * abs(evals[1]):
            quadratic_matrix += np.ones / np.sqrt(quadratic_matrix.shape[0])

    return quadratic_matrix
```
in coil_optimize.py line 506 - 511

Is the np.ones missing an augument?
I am not sure when we get in to this `if deflate` though, so I am not sure how to reproduce it.

**Comment by rzetter** [comment]
Oops, this is definitely a bug. The deflate parameter is True by default, so this code block is always executed when preparing the quadratic objective in stream function optimization. 

The second if-clause however should only be triggered by matrices stemming from closed surfaces. The if-clause checks whether the smallest eigenvalue of the quadratic objective matrix (e.g. inductance matrix, resistance matrix) is dramatically smaller than the second-smallest eigenvalue. 

What the code following the second if-clause is supposed to do is to "deactivate" that smallest eigenvalue by adding a new "neutral" eigenvalue that is larger than any of the ones (ping @anttimc). Without this operation the quadratic matrix might not be positive semi-definitive (which is a requirement for the optimization algorithms) or it may have other numerical issues.

I've fixed the bug(6a5d693f9f212a857081e5a1a7928b216de69e09, c2ca14ecd55f6317b9db5bc72a04242300b64b47) and added a log message for when the deflation is triggered. I'll create a new bugfix version as well so you can just update via pip :)
