### ISSUE TITLE
Magnetic potential normalization for linear conductors

### ISSUE THREAD

**Issue by SAFedorov** [bfieldtools/bfieldtools#37]
Hi,
The relation between scalar_potential and magnetic_field from line_magnetics seems to be B = grad(U), which is different from B = -mu0*grad(U) assumed everywhere else and provided in the theory paper. I noticed this when calculating the magnetic field produced by a current loop inside a magnetic shield, because at first matching the scalar potentials created by the loop and the shield surface currents produced inconsistent results. I checked for a simple geometry that the magnetic field of a loop is correct, so it could be that scalar_potential misses a normalization factor.

**Comment by rzetter** [comment]
Thanks for this bug report, something does seem to be amiss! @anttimc, would you have time to look at this?

**Comment by anttimc** [comment]
Hello, just by looking at the code it seems that line_magnetics does not have the correct normalization factor. Also, according to the description by @SAFedorov, the sign is wrong. I remember that the scalar potential for line conductor loops was a late addition not probably well tested. 

@SAFedorov if your code could be modified to a test with a little effort, you could add that test (new file like tests/test_line_magnetics.py) and correct the normalization (which should be  1/(4*pi) I guess) for scalar_potential in line_magnetics.py in a pull request.

**Comment by SAFedorov** [comment]
Ok, I can do this.

**Comment by anttimc** [comment]
Closed by the merge of PR #39
