### ISSUE TITLE
Create new mesh xxx.obj. It doesn't work.

### ISSUE THREAD

**Issue by hbbdyzf** [bfieldtools/bfieldtools#38]
I use blender to create a new mesh. the code has ''ValueError: Mesh with name 3212_plane not found in example_meshes folder''. I have put the 3212_plane.obj in the .....\bfieldtools\example_meshes. Why it is.

**Comment by rzetter** [comment]
Hi! You seem to be using the function bfieldtools.utils.load_example_mesh(...) to load your own meshes. In principle you can add your own example meshes, but if you've installed bfieldtools (e.g. using pip), you'll have to put your own meshes in the installation folder. 

I'd recommend that instead, you do one of the two things below:

1. Load the mesh as a trimesh object (trimesh is a dependency of bfieldtools which handles most mesh-related functionality)
```
import trimesh
mesh = trimesh.load(file_obj='/path/to/mesh.obj')
```

2. Directly load the mesh into a bfieldtools MeshConductor, much in the same way as the first method. 
```
from bfieldtools.mesh_conductor import MeshConductor
conductor_object = MeshConductor(mesh_file='/path/to/mesh.obj')
```
 

I hope this helps!

**Comment by hbbdyzf** [comment]
OK，it works.
Thank you!
