### ISSUE TITLE
Dunavant quadrature missing

### ISSUE THREAD

**Issue by GBZH** [bfieldtools/bfieldtools#44]
Hello,

In order to install bfieldtools, I had to modify the requirements.txt file as there was an incompatibility between quadpy and orthopy. The only available version for orthopy is now 0.9.6 which requires qudpy >= 0.16.8 whereas in requirements.txt it is required to use quadpy <= 0.15.0.
Excpet for that, the bfieldtools installation ran well.
Unfortunately, when trying to play a simple exemple from the distribution, it seems that some quadratures methods are missing as can be seen below.

```
$> python biplanar_coil_design.py                                                          

Invalid MIT-MAGIC-COOKIE-1 keyCalculating surface harmonics expansion...
Computing the laplacian matrix...
Computing the mass matrix...
Computing magnetic field coupling matrix, 3184 vertices by 160 target points... Traceback (most recent call last):
  File "biplanar_coil_design.py", line 89, in <module>
    "coupling": coil.B_coupling(target_points),
  File "/home/quemener/local/bfieldtools/bfieldtools/mesh_conductor.py", line 638, in __call__
    self.matrix = self.function(self.parent.mesh, points, *fun_args, **kwargs)
  File "/home/quemener/local/bfieldtools/bfieldtools/mesh_magnetics.py", line 65, in magnetic_field_coupling
    w_quad, r_quad = get_quad_points(
  File "/home/quemener/local/bfieldtools/bfieldtools/utils.py", line 108, in get_quad_points
    raise ValueError(
ValueError: method: dunavant_01 not in the available list of quadrature methods (check triangle.__all__)
```

Does anyone have some hints on how to fix that ? Does anyone have the good versions of orthopy and quadpy available somewhere ?
Many thanks in advance for your help.

**Comment by mbarbattini** [comment]
Pull request #45 fixed this issue. The version of quady remained the same, but the loading scheme of the methods were changed instead.
