### ISSUE TITLE
the way to devide streamfunction into loops

### ISSUE THREAD

**Issue by 3masa25smile** [bfieldtools/bfieldtools#49]
I would like to know how to change the way to devide streamfunction into loops.
In defalt, I think the way to devide streamfunction is the following.
coil.s.discretize(N_contours=config["N_contours"])
(according to bfieldtools/contours.py, if contours is None: contours = np.linspace(scalars.min(), scalars.max(), 2 * N_contours + 1)[1::2] )

According to discretize's options, we can change the way to devide streamfunction from defalt settings like follwing.
coil.s.discretize(N_contours=config["N_contours"], contours=contours)

I tried to use this options like following example code, but got unexpected windings. I would like to know solutions.

windings by coil.s.discretize(N_contours=config["N_contours"])
![windings](https://user-images.githubusercontent.com/112611319/191178057-2fa45013-3e19-49e0-9286-ba0b636b6c27.png)

windings by coil.s.discretize(N_contours=config["N_contours"], contours=contours)
![windings](https://user-images.githubusercontent.com/112611319/191177701-0fae46fb-c7c0-4d85-8223-8de07babdaaa.png)

code
```
"""
https://bfieldtools.github.io/auto_examples/coil_design/biplanar_coil_design.html#sphx-glr-auto-examples-coil-design-biplanar-coil-design-py

Biplanar coil design
====================

Example showing a basic biplanar coil producing homogeneous field in a target
region between the two coil planes.

"""

import numpy as np
import matplotlib.pyplot as plt
from mayavi import mlab
import trimesh


from bfieldtools.mesh_conductor import MeshConductor
from bfieldtools.coil_optimize import optimize_streamfunctions
from bfieldtools.viz import plot_cross_section
from bfieldtools.utils import combine_meshes, load_example_mesh


# Load simple plane mesh that is centered on the origin
planemesh = load_example_mesh("10x10_plane_hires")

# Specify coil plane geometry
center_offset = np.array([0, 0, 0])
standoff = np.array([0, 3, 0])

# Create coil plane pairs
coil_plus = trimesh.Trimesh(
    planemesh.vertices + center_offset + standoff, planemesh.faces, process=False
)

coil_minus = trimesh.Trimesh(
    planemesh.vertices + center_offset - standoff, planemesh.faces, process=False
)

joined_planes = combine_meshes((coil_plus, coil_minus))

# Create mesh class object
coil = MeshConductor(
    mesh_obj=joined_planes, fix_normals=True, basis_name="suh", N_suh=100
)

#%%
# Set up target and stray field points

# Here, the target points are on a volumetric grid within a sphere

center = np.array([0, 0, 0])

sidelength = 1.5
n = 8
xx = np.linspace(-sidelength / 2, sidelength / 2, n)
yy = np.linspace(-sidelength / 2, sidelength / 2, n)
zz = np.linspace(-sidelength / 2, sidelength / 2, n)
X, Y, Z = np.meshgrid(xx, yy, zz, indexing="ij")

x = X.ravel()
y = Y.ravel()
z = Z.ravel()

target_points = np.array([x, y, z]).T

# Turn cube into sphere by rejecting points "in the corners"
target_points = (
    target_points[np.linalg.norm(target_points, axis=1) < sidelength / 2] + center
)


# Here, the stray field points are on a spherical surface
stray_radius = 20
stray_points_mesh = trimesh.creation.icosphere(subdivisions=3, radius=stray_radius)
stray_points = stray_points_mesh.vertices + center

n_stray_points = len(stray_points)


#%%
# Create bfield specifications used when optimizing the coil geometry

# The absolute target field amplitude is not of importance,
# and it is scaled to match the C matrix in the optimization function

target_field = np.zeros(target_points.shape)
target_field[:, 0] += 1

target_spec = {
    "coupling": coil.B_coupling(target_points),
    "abs_error": 0.01,
    "target": target_field,
}
stray_spec = {
    "coupling": coil.B_coupling(stray_points),
    "abs_error": 0.01,
    "target": np.zeros((n_stray_points, 3)),
}

bfield_specification = [target_spec, stray_spec]

#%%
## Compute the optimal stream function, either using a numerical solver or regularized least squares

import mosek

coil.s, prob = optimize_streamfunctions(
    coil,
    [target_spec, stray_spec],
    objective="minimum_ohmic_power",
    solver="MOSEK",
    solver_opts={"mosek_params": {mosek.iparam.num_threads: 8}},
)


#%%
# Plot the optimized stream function, then discretize it and plot coil windings and the resultant magnetic field

N_contours=4
loops = coil.s.discretize(N_contours=N_contours)

# change way to devide streamfunction
contours = np.linspace(coil.mesh.vertices.min(), coil.mesh.vertices.max(), 2 * N_contours + 1)[1::2]
# print(contours)
# TrackedArray([-1.875, -0.625,  0.625,  1.875])
# change
contours[1] = -0.1
contours[-2] = 0.1
# print(contours)
# TrackedArray([-1.875, -0.5  ,  0.5  ,  1.875])
loops = coil.s.discretize(N_contours=N_contours, contours=contours)
```

**Comment by rzetter** [comment]
Hi!

The issue you're having is on this specific line of your example:
`contours = np.linspace(coil.mesh.vertices.min(), coil.mesh.vertices.max(), 2 * N_contours + 1)[1::2]`

The coil.mesh.vertices corresponds to the geometry of the mesh (the positions of the vertices) rather than the value of the optimized stream function at those vertices. If you change that line to
`contours = np.linspace(coil.s.vert.min(), coil.s.vert.max(), 2 * N_contours + 1)[1::2]`

Note that since the the stream function (coil.s) was optimized in the surface harmonics (suh) basis, to get proper contours we must transfer it to the vertex basis (easiest done by using coil.s.vert) in order to get the vertex-wise values.

The resulting contours array is 
`array([-9122116.91786846, -3040582.22582223,  3040952.46622401,
        9122487.15827024])`
and `loops.plot_loops()` looks like this
![image](https://user-images.githubusercontent.com/39831259/191191546-6878ec3c-bfb4-4e0f-a093-2819a0187ae3.png)

**Comment by 3masa25smile** [comment]
Thank you! 
I understood that better way is done by using coil.s.vert.
I tried it!

**Comment by 3masa25smile** [comment]
I succeeded in ussing contours-change option. Thank you.

I have another question. How is the benefit to use contours-change option coil.s.discretize(N_contours=config["N_contours"], **_contours=contours_**)?

I tried to use contours-change option( I changed the specific value to different value) based on my curiosity. As a result, the uniformity went down compared to defalt contours setting. I think windings by contours-change option can not reproduce the optimized current density worse compared to windings by defalt setting. So, what kind of situation should I use this option?

**Comment by rzetter** [comment]
Hi! 

The default option is indeed the best for most use-cases. There are some specific cases where one may want more explicit control of where the contours are placed, e.g. when there are holes in the surface current mesh and small changes in the contouring makes the discretized loops "jump" to be either around a hole or not.

**Comment by 3masa25smile** [comment]
Thank you for good advice and example!
