### ISSUE TITLE
Quadpy now proprietary?

### ISSUE THREAD

**Issue by rzetter** [bfieldtools/bfieldtools#53]
Hi all, the shadiness going on with Quadpy already observed here: https://github.com/bfieldtools/bfieldtools/pull/45 has now continued. The package now is a) disibuted with encrypted code and b) checks for some undocumented "Sigma license". I asked the main author about it here: https://github.com/sigma-py/quadpy/issues/462

Tagging @anttimc  and @jiivana for awareness as it seems bfieldtools in its current state cannot be used with the newer quadpy versions (and the older ones have been removed from PyPI). The old GPL-licensed versions are still available via Zenodo though, e.g: https://zenodo.org/record/5541216

**Comment by anttimc** [comment]
If I remember right we use only very simple quadrature rules. We could make a new module and implement the rules we use there and get rid of quadpy dependency. It was always sort of nice-to-have thing.

**Comment by rzetter** [comment]
Yeah, I guess that's the way to go. Reducing the number of dependencies doesn't hurt anyway.

**Comment by anttimc** [comment]
I started sketching the module. Next I'll check what other rules we use and take the new module in use.

**Comment by anttimc** [comment]
@rzetter PR ready for review 
😉

**Comment by rzetter** [comment]
Wow, you were really quick! In all honesty, I didn't expect you to grab onto this now, kudos!

I'll try to review this as quickly ;)

**Comment by rzetter** [comment]
Closed by PR#54
