### ISSUE TITLE
could not run example for zeroing field in z-direction

### ISSUE THREAD

**Issue by jasmainak** [bfieldtools/bfieldtools#56]
Hey guys,

Together with @padmasundaram I tried running the [biplanar coil design](https://bfieldtools.github.io/auto_examples/publication_software/pub_biplanar_coil_design.html#sphx-glr-auto-examples-publication-software-pub-biplanar-coil-design-py) example and at first it ran fine, but I wanted to play around with it to see if I could get the field to be 0 in the z-direction. So I modified this line:

```py
target_field[:, 0] += 1 
```

to 

```py
target_field[:, 1] += 1 
```

But the example crashes (see below) because the solver does not converge. Any clues where I might be going wrong? Thanks a ton!

```py
TypeError                                 Traceback (most recent call last)
File /autofs/cluster/fusion/padma/MEG/OPM_coils/git_biplanar_coil_design.py:106
    101 #%%
    102 ## Compute the optimal stream function, either using a numerical solver or regularized least squares
    104 import mosek
--> 106 coil.s, prob = optimize_streamfunctions(
    107     coil,
    108     [target_spec, stray_spec],
    109     objective="minimum_ohmic_power",
    110     solver="MOSEK",
    111     solver_opts={"mosek_params": {mosek.iparam.num_threads: 8}},
    112 )
    115 #%%
    116 # Plot the optimized stream function, then discretize it and plot coil windings and the resultant magnetic field
    118 coil.s.plot()

File /cluster/fusion/padma/anaconda3/envs/bfieldtools/lib/python3.8/site-packages/bfieldtools/coil_optimize.py:308, in optimize_streamfunctions(mesh_conductor, bfield_specification, objective, solver, solver_opts, problem, DPP)
    304 problem.solve(solver=solver, verbose=True, **solver_opts)
    306 # extract optimized streamfunction, scale by same singular value as constraint matrix
    307 S = StreamFunction(
--> 308     problem.variables()[0].value / s[0], mesh_conductor=mesh_conductor
    309 )
    311 return S, problem

TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by rzetter** [comment]
Hi! This issue relates to the use of the surface harmonics "suh" basis in the Mesh conductor object and the geometry.
 
 If you run

coil.suh_basis.plot(Nfuncs=10)

with the ‘coil’ object from the script you quote, you’ll get the plot below:

 


 

In the plot you can see that each surface harmonic basis function (you can think of this like a Fourier series) is identical on either surface. This means that the stream functions are forced to be symmetrical on either surface. You can of course remove the use of the surface harmonic basis and instead use the default “inner” basis in which every mesh triangle is independent. This is computationally slower but gets rids of the issue.


coil = MeshConductor(
    mesh_obj=joined_planes, fix_normals=True, basis_name="inner"
)
 

Another way, which I haven’t truly integrated into bfieldtools proper yet, is to build surface harmonic bases for each individual surface, and then append these after each other. For this approach, replace the first block of the biplanar_coil_design.py with the code below. I’ve commented some of the changes, they are at the end of the block.

import numpy as np
import matplotlib.pyplot as plt
from mayavi import mlab
import trimesh
 
 
from bfieldtools.mesh_conductor import MeshConductor
from bfieldtools.coil_optimize import optimize_streamfunctions
from bfieldtools.viz import plot_cross_section
from bfieldtools.utils import combine_meshes, load_example_mesh
 
 
# Load simple plane mesh that is centered on the origin
planemesh = load_example_mesh("10x10_plane_hires")
 
# Specify coil plane geometry
center_offset = np.array([0, 0, 0])
standoff = np.array([0, 3, 0])
 
# Create coil plane pairs
coil_plus = trimesh.Trimesh(
    planemesh.vertices + center_offset + standoff, planemesh.faces, process=False
)
 
coil_minus = trimesh.Trimesh(
    planemesh.vertices + center_offset - standoff, planemesh.faces, process=False
)
 
joined_planes = combine_meshes((coil_plus, coil_minus))
 
 
import scipy
from scipy.sparse import csr_matrix
#Create separate surface harmonic bases for the planes
coil_plus_C = MeshConductor(mesh_obj=coil_plus, basis_name='suh', N_suh=300, process=False) #Change the number 300 as desired
coil_minus_C = MeshConductor(mesh_obj=coil_minus, basis_name='suh', N_suh=300, process=False)
 
#Combine the separate bases stacked "on top of each other"
stacked_basis = scipy.linalg.block_diag(coil_plus_C.basis, coil_minus_C.basis)
 
#Combine the basis transformation matrices
stacked_inner2vert = csr_matrix(scipy.linalg.block_diag(coil_plus_C.inner2vert.toarray(), coil_minus_C.inner2vert.toarray()))
stacked_vert2inner = csr_matrix(scipy.linalg.block_diag(coil_plus_C.vert2inner.toarray(), coil_minus_C.vert2inner.toarray()))
 
#Create a MeshConductor with both planes but a "dummy" basis choice
coil = MeshConductor(mesh_obj=joined_planes,
                                   basis_name='inner', N_suh=10, process=False) #Number of harmonics not important here, will not be used
 
#Overwrite dummy basis with stacked basis
coil.basis = stacked_basis
coil.inner2vert = stacked_inner2vert
coil.vert2inner = stacked_vert2inner


Using the adapted code above, the surface harmonic series is now separate for each surface. When plotting the 10 first basis functions, we see that the other surface is simply at zero. These functions are of course followed by the corresponding functions for the other surface.
 


 

I hope this helps, let me know if you have any questions or issues! :)

 

All the best,

Rasmus

**Comment by jasmainak** [comment]
Thank you! That worked like a charm! Now I tried to make the gradient field zero by doing the following:

```py
target_field_y = np.linspace(0, 1, n)
target_field_x = target_field_z = np.zeros((n,))
tf_X, tf_Y, tf_Z = np.meshgrid(target_field_x, target_field_y, target_field_z, indexing='ij')
target_field = np.array([tf_X.ravel(), tf_Y.ravel(), tf_Z.ravel()]).T
```

but this fails to converge. We thought maybe the issue is that the harmonics cannot cancel such large gradients, so when I tried:

```py
target_field_y = np.linspace(0.8, 1, n)
```

and increased the tolerance for convergence, that begins to work. However, that made us wonder what are the units of the target field? I know you mentioned somewhere in the docs that the units don't matter but since we are measuring fields in nT and nT/m in the real world, how can we translate that into the code here?

**Comment by rzetter** [comment]
Hi again! This gradient spec failing to converge is simply since it's not physically possible. That's also why increasing the tolerance makes the problem converge.  The Jacobian matrix  of the magnetic field is symmetric, and the determinant is always zero. Thus one can it create a gradient in one direction without simultaneously creating a so-called concomitant gradient in another direction.

When creating gradients, it's convenient to set the target field specification via the use of spherical harmonics coefficients, which capture thus behaviour. There's several examples on the bfieldtools website. You can either use them to simply get the target field values or optimize the stream functions fully in a spherical-harmonics framework.

Ps. If you're looking for some large field-nulling coils for OPM-MEG, e.g. in the same MSR as your SQUID system, I/Megin can help with that, we have a ready-made solution.

**Comment by jasmainak** [comment]
Got it, thanks for explaining! We'll try a bit more and get back if we have more questions. 

Btw -- regarding field-nulling coils. Yes, we are looking for something for OPM-MEG and it would be fantastic to have a ready-made solution. We are trying to move away from the 3-layer room and build something for the 1-layer room but it might be worth exploring the solution you mention. Perhaps we could discuss more with @padmasundaram over a zoom call next week or the week after? I can shoot you an email to schedule this if you agree.

**Comment by jasmainak** [comment]
Hi again @rzetter, following your advice, we tried using the spherical harmonics to set the gradients but have been unsuccessful so far. Is there some documentation/explanation somewhere which spherical harmonic components to use for which gradient components? We would like to cancel dBx/dy, dBy/dy, and dBz/dy (y direction going between the panels) ... basically ones that can be explained by a maxwell pair (also as in the [Brookes papers](https://www.sciencedirect.com/science/article/pii/S1053811918306438)). Playing around with the spherical harmonics and reading your examples, it seems that `blm[0]` to `blm[2]` give a DC field while `alm[0]` to `alm[2]` give a gradient along z (up-down) but not along y. How can we get a gradient between the panels with the spherical harmonics? Thank you once again for your help with using the package!
