### ISSUE TITLE
Question on Specifying the Target Field

### ISSUE THREAD

**Issue by jamie2minchae** [bfieldtools/bfieldtools#60]
### Discussed in https://github.com/bfieldtools/bfieldtools/discussions/59

<div type='discussions-op-text'>

<sup>Originally posted by **jamie2minchae** August 18, 2023</sup>
Thank you for creating such wonderful software. I have a question on specifying the target field.

 For us, only the z-component of the target magnetic field matters and it is not necessary to specify the (x, y)-components.

 However, I think that the (x, y, z)-components of the target field should be specified simultaneously, which will likely impose extra constraints on coil designs. Note that setting (x, y)=(0, 0) is an explicit specification of the target field, and we would rather want the coil design not to care about the generated (x, y)-fields, which can potentially have arbitrary values.

Can you help us on implementing this in your bfieldtools software package?

Perhaps the "optimize_streamfunction" can only use the z-component of the target field to generate optimal coil designs, or the weight of the (x, y)-target-field constraints can be tuned down within the software. However, we are not sure on how to implement this. We are using the object "minimum_Ohmic_power".

Your fast response will be very much appreciated. Thank you in advance.
</div>

**Comment by rzetter** [comment]
Responded in discussion section, check it out!
